name: Updating ostree repository
on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  update-ostree-repo:
    runs-on: ubuntu-22.04
    container:
      image: fedora:latest
      options: --name=fedora-container --cap-add CAP_SYS_ADMIN
      volumes:
        - /mnt/fedora-container:/mnt/rpm-ostree-repo
    steps:
      - name: Checking out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Fedora Tool
        run: bash build_rpm-ostree_repo.sh
