name: Updating ostree repository
on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  update-ostree-repo:
    runs-on: ubuntu-22.04
    container:
      image: fedora:latest
      options: --name=fedora-container --cap-add CAP_SYS_ADMIN --privileged
    steps:
      - name: Checking out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build ostree repo
        run: bash build_rpm-ostree_repo.sh

      - name: Pushing to ostree branch
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          # Disable setting repo owner as commit author
          commit_user_name: github-actions[bot]
          commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
          commit_author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>

          # Optional. Commit message for the created commit.
          # Defaults to "Apply automatic changes"
          commit_message: Update ostree branch
          branch: ostree-repo
          create_branch: true
          # Only include needed files
          # file_pattern: './*'
          # push_options: '--force'
          
